<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>CA1416</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FacturasApp.Core\FacturasApp.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Docnet.Core" Version="2.7.0-alpha.1" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
	</ItemGroup>

	<!-- Tessdata para OCR -->
	<ItemGroup>
		<Content Include="..\tessdata\spa.traineddata" Link="tessdata\spa.traineddata">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Publish>true</Publish>
		</Content>
		<Content Include="..\tessdata\eng.traineddata" Link="tessdata\eng.traineddata">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Publish>true</Publish>
		</Content>
	</ItemGroup>

</Project>
