<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FacturasApp.Core\FacturasApp.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="PdfiumViewer.Updated" Version="2.14.5" />
		<PackageReference Include="bblanchon.PDFium.Win32" Version="139.0.7215" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
	</ItemGroup>

	<!-- Tessdata para OCR -->
	<ItemGroup>
		<Content Include="..\tessdata\spa.traineddata" Link="tessdata\spa.traineddata">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Publish>true</Publish>
		</Content>
		<Content Include="..\tessdata\eng.traineddata" Link="tessdata\eng.traineddata">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Publish>true</Publish>
		</Content>
	</ItemGroup>

</Project>
