<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>

		<ApplicationIcon>Assets/app-icon.ico</ApplicationIcon>
		
		<!-- Versionado -->
		<Version>3.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		
		<!-- Información de la aplicación -->
		<Company>FacturasApp</Company>
		<Product>FacturasApp</Product>
		<Description>Aplicación para procesar y gestionar facturas</Description>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Data\plantillas_ocr.xml" />
		<None Remove="tessdata\eng.traineddata" />
		<None Remove="tessdata\spa.traineddata" />
	</ItemGroup>

	<!-- Archivo de plantillas: incrustado en el ensamblado -->
	<ItemGroup>
		<EmbeddedResource Include="Data\plantillas_ocr.xml">
			<LogicalName>FacturasApp.Data.plantillas_ocr.xml</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Data\Emisores\*.xml">
			<LogicalName>FacturasApp.Data.Emisores.%(Filename)%(Extension)</LogicalName>
		</EmbeddedResource>
		<Compile Remove="Tests\**" />
		<EmbeddedResource Remove="Tests\**" />
		<None Remove="Tests\**" />
		
		<!-- Archivos de Tesseract (copiados normalmente) -->
		<Content Include="tessdata\eng.traineddata">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Publish>true</Publish>
		</Content>
		<Content Include="tessdata\spa.traineddata">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Publish>true</Publish>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="PdfiumViewer.Updated" Version="2.14.5" />
		<PackageReference Include="bblanchon.PDFium.Win32" Version="139.0.7215" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="FacturasApp\UI\DetalleFacturaForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="FacturasApp\UI\MainForm.cs">
			<SubType>Form</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="FacturasApp\UI\MainForm.resx">
			<SubType>Designer</SubType>
		</EmbeddedResource>
	</ItemGroup>

</Project>