<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>FacturasApp.Core</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Data\plantillas_ocr.xml" />
	</ItemGroup>

	<!-- Archivo de plantillas: incrustado en el ensamblado -->
	<ItemGroup>
		<EmbeddedResource Include="Data\plantillas_ocr.xml">
			<LogicalName>FacturasApp.Core.Data.plantillas_ocr.xml</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Data\Emisores\*.xml">
			<LogicalName>FacturasApp.Core.Data.Emisores.%(Filename)%(Extension)</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
	</ItemGroup>

</Project>
